#include <cs50.h>
#include <stdio.h>
#include <crypt.h>
#include <string.h>
// Array to hold the salt(first two characters of the hashed password)
char salt[2];
int main(int argc, string argv[])
{
    if (argc != 2)
    {
        printf("Error: Please provide only 1 command line argument\n");
        return 1;
    }
    //Allocates array to hold the password
    char password[6];
    //Assigns the last character for the password holder  array to be a null terminator
    password[5] = '\0';
    //Allocates array to hold all large and small alphabetical letters
    char letters[52];
    //Assigns the first two elements of the second command line argument to be used as the salt for the crypt function
    salt[0] = argv[1][0];
    salt[1] = argv[1][1];
    int i;
    int j;
    //Iterates over all the alphabetic characters and stores them in an array
    for (i = 65, j = 0; j < 52; i++, j++)
    {
        if (i == 91)
        {
            i = 97;
        }
        letters[j] = i;
    }
    // Itterates over all the characters stored in the array
    for (i = 0; i < 52; i++)
    {
        //Asigns the first character of the password array to each of the characters from the letter array
        password[0] = letters[i];
        //Checks if the crypt function of the password array generated by alphabetical characters and salt is equal to the hashed password given by the user
        if (strcmp(crypt(password, salt), argv[1]) == 0)
        {
            //If so print the password and return 0 to exit the main function
            printf("%s\n", password);
            return 0;
        }
    }
    //Does the same as the previous loop block, with the exception that it checks if the password is two characters long
    for (i = 0; i < 52; i++)
    {
        password[0] = letters[i];
        {
            for (j = 0; j < 52; j++)
            {
                password[1] = letters[j];
                if (strcmp(crypt(password, salt), argv[1]) == 0)
                {
                    printf("%s\n", password);
                    return 0;
                }
            }
        }
    }
    //Does the same as the previous loop block, with the exception that it checks if the password is three characters long
    for (i = 0; i < 52; i++)
    {
        password[0] = letters[i];
        {
            for (j = 0; j < 52; j++)
            {
                password[1] = letters[j];
                for (int k = 0; k < 52; k++)
                {
                    password[2] = letters[k];
                    if (strcmp(crypt(password, salt), argv[1]) == 0)
                    {
                        printf("%s\n", password);
                        return 0;
                    }
                }
            }
        }
    }
    //Does the same as the previous loop block, with the exception that it checks if the password is four characters long
    for (i = 0; i < 52; i++)
    {
        password[0] = letters[i];
        {
            for (j = 0; j < 52; j++)
            {
                password[1] = letters[j];
                for (int k = 0; k < 52; k++)
                {
                    password[2] = letters[k];
                    for (int l = 0; l < 52; l++)
                    {
                        password[3] = letters[l];
                        if (strcmp(crypt(password, salt), argv[1]) == 0)
                        {
                            printf("%s\n", password);
                            return 0;
                        }
                    }

                }
            }
        }
    }
    //Does the same as the previous loop block, with the exception that it checks if the password is five characters long
    for (i = 0; i < 52; i++)
    {
        password[0] = letters[i];
        {
            for (j = 0; j < 52; j++)
            {
                password[1] = letters[j];
                for (int k = 0; k < 52; k++)
                {
                    password[2] = letters[k];
                    for (int l = 0; l < 52; l++)
                    {
                        password[3] = letters[l];
                        for (int m = 0; m < 52; m++)
                        {
                            password[4] = letters[m];
                            if (strcmp(crypt(password, salt), argv[1]) == 0)
                            {
                                printf("%s\n", password);
                                return 0;
                            }
                        }

                    }

                }
            }
        }
    }
}
